FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY server.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://+:9111
ENV FitTrack__DbPath=/data/fittrack.db

COPY --from=build /app/publish ./

VOLUME ["/data"]

EXPOSE 9111

ENTRYPOINT ["dotnet", "server.dll"]
